import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../pages/navbar'
import Title from '../pages/title'
import Filter from '../pages/componenets/filter'
import Portfolio from '../pages/portfolio/portfolio'
import Footer from '../pages/footer'

export default function Home() {
  return (
    <div>
    
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar></Navbar>
    <div className={'pt-56 2lg:mx-72 lg:mx-40 md:mx-20 sm:mx-20 mx-10 animate'}>
    <Title></Title>
    <Filter></Filter>
    </div>
    
    <Portfolio></Portfolio>
    <Footer></Footer>
    </div>
    )
  }
  